### ISSUE TITLE
We cannot obtain the same results as the images in the paper on the demo of Huggingface

### ISSUE THREAD

**Issue by yatoubusha** [yardenfren1996/B-LoRA#18]
I tried to get Figure 3 in the paper, but in reality I got Figure 1. Figure 2 is my configuration. Does this effect rely heavily on card draws? Or does my configuration need to be changed?

![image](https://github.com/user-attachments/assets/9f202f2e-839c-46b0-a769-af7f760c7b00)

![image](https://github.com/user-attachments/assets/ef81a272-d240-482b-a1a2-8000681c20ca)

![image](https://github.com/user-attachments/assets/02ae865d-01e7-412f-9e79-e701ffaffa45)

**Comment by yardenfren1996** [comment]
Hi @yatoubusha.
For recontextualization, I trained using multiple images of the same object. (unlike our implicit method that using a single image.)

The model of the cat was trained on single image, causing it to struggle with recontextualization, which is a common issue with personalized methods.

All the models I have uploaded to the demo were trained on single images, except for one: `lora-library/B-LoRA-multi-dog2`. (Please note the 'multi' in the name; I'll add more in the future).

You can use this specific LoRA model for this task.

![Screenshot 2024-07-18 at 12 14 51](https://github.com/user-attachments/assets/2ab680a8-fb03-4ead-9133-151286b8b53c)
