### ISSUE TITLE
Question about multi images training

### ISSUE THREAD

**Issue by yatoubusha** [yardenfren1996/B-LoRA#19]
Thank you for your answer about issue #18, If I want to use multiple images to train content Lora, do I need to make any changes to the training code besides preparing the dataset?

**Comment by yardenfren1996** [comment]
No @yatoubusha , you don't need any additional changes except for the prompt. 
To get better results (since we don't need to keep the structure of the image), you should use the prompt `"A [v] {class_name}"` as suggested by the authors of Dreambooth in their paper.
