### ISSUE TITLE
Request for instance prompts

### ISSUE THREAD

**Issue by jychoi118** [yardenfren1996/B-LoRA#2]
Thank you for open-sourcing awesome work!

Can you share instance prompts used for fine-tuning on each style images?

Compared to the content prompt [c], It's hard for me to come up with style prompt [s] that clearly describe style images.

Or did you literally use "A [v]"?

**Comment by jychoi118** [comment]
Oh my bad, you used "A [v]"

**Comment by yardenfren1996** [comment]
Hi @jychoi118, in this case, you are absolutely correct. We use only the prompt "A [v]" without the need to describe the style image  (this is one of the reasons why our method is implicit). I refer you to the supplementary material section C, where we conducted an ablation study regarding Prompt Selection. If you have any other questions, I will be happy to help.

**Comment by jychoi118** [comment]
Thank you for your responce!
