### ISSUE TITLE
Curious and splitted results

### ISSUE THREAD

**Issue by clementjambon** [yardenfren1996/B-LoRA#20]
I tried to play with your pre-trained LoRA weights (using directly https://github.com/yardenfren1996/B-LoRA/blob/main/B_LoRA_inference.ipynb) and I get very curious results.

For "Image Stylization Based On Text Reference", when using the prompt "A [v3] made of gold", things look fine (although not similar). However, using other materials such as "A [v3] made of wood" yields extremely weird results like this:
![image (19)](https://github.com/user-attachments/assets/1fd6b8ee-71ab-45bc-b1f0-e2f48ac3ca72)

When running exactly the example for "Consistent Style Generation", I get splitted results too
![image (20)](https://github.com/user-attachments/assets/db955fd0-eb06-42fe-b913-6bc4bb8be69f)

**Comment by yardenfren1996** [comment]
Hi, @clementjambon 

Thanks for reaching out.

We are aware that some "bad seeds" may yield weird results when using our method. In your example, seed 48 did not work well with the prompt "A [v3] made of wood." To investigate further, I randomly selected another 9 seeds, generated 10 results in total, and plotted them in the following image: 

![Screenshot 2024-07-24 at 13 09 48](https://github.com/user-attachments/assets/4726d384-c53b-4923-b343-c596fb27ee18)


As you can see, our method is consistent with 8 out of 10 different seeds. (except 48, 668)

We are confident in our results, but sometimes using a different seed or adjusting the alpha can improve them even further.
Thank you.
