### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by Reginald-L** [yardenfren1996/B-LoRA#21]
Great job. 
My question: How do you get the idea? w4 is good for content feature and w5 is good for style feature? attention map visualisation?

**Comment by yardenfren1996** [comment]
Thank you @Reginald-L !
Actually, we didn't use attention map visualization, although it might sound like a good idea for validation.
In our experiments, we used prompt injection at different layers within SDXL's Unet architecture.
You can find more details in Section 4.1 in the paper (Figure 4). You can also watch the motivation video for this experiment [here](https://b-lora.github.io/B-LoRA/#:~:text=Image%20Style%20Reference-,How%20does%20it%20work%3F,-Our%20method%20leverages) and see the ablations in Figures 16-17 in the supp.
