### ISSUE TITLE
Update readme with instructions for getting this to work on Windows 10 (here's what I did)

### ISSUE THREAD

**Issue by lendrick** [yardenfren1996/B-LoRA#6]
I've got this working with CUDA 12.1 on Windows.  

Immediately after creating the conda environment, install CUDA PyTorch:

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

Then, pip install -r requirements.txt as normal.

After that:

pip uninstall bitsandbytes

python -m pip install bitsandbytes --prefer-binary --extra-index-url=https://jllllll.github.io/bitsandbytes-windows-webui

(yes, I called pip three different ways, because I copied these lines from various places on the internet, but it worked)

**Comment by yardenfren1996** [comment]
Done
