### ISSUE TITLE
Document how to convert lora for use in a1111 and comfy

### ISSUE THREAD

**Issue by lendrick** [yardenfren1996/B-LoRA#7]
I used this script here (which happily runs in this repo's conda environment):

https://github.com/huggingface/diffusers/blob/main/scripts/convert_diffusers_sdxl_lora_to_webui.py

I had to dig around to find it, because I'm not a diffusers user.  It would be a handy addition to the readme file. :)

**Comment by yardenfren1996** [comment]
Done. Thank you

**Comment by yatoubusha** [comment]
my diffusers is 0.25.0 which is required by this repo, but i got this error: [cannot import name 'convert_all_state_dict_to_peft' from 'diffusers.utils']

**Comment by yatoubusha** [comment]
> I used this script here (which happily runs in this repo's conda environment):
> 
> https://github.com/huggingface/diffusers/blob/main/scripts/convert_diffusers_sdxl_lora_to_webui.py
> 
> I had to dig around to find it, because I'm not a diffusers user. It would be a handy addition to the readme file. :)

which version do you use about diffusers?
