### ISSUE TITLE
a conflict in paper?

### ISSUE THREAD

**Issue by laolongboy** [yardenfren1996/B-LoRA#9]
"We present the results of these experiments in Figure 15. Our findings indicate that injecting the prompt “A [c]” into
W4 while other blocks receive the prompt “A [c] in [s] style” often leads to improved generation results, particularly for complex scenes containing numerous elements."

But in caption of Figure 15, it says:
(5) Similar to 3, but injecting “A [s]” into W5 while other blocks receive our method’s prompt “A [c] in [s] style”. As can be seen the (5) columns contains the best results.

**Comment by yardenfren1996** [comment]
Hi @laolongboy , thank you for bringing this mistake to our attention. After reviewing it, we found that there is indeed an error in the caption; the text is accurate ( “A [c]” into W4 while other blocks receive the prompt “A [c] in [s] style”). We will update it as soon as possible.
Thank you for notifying us.
